//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillProduct
    {
        public int billProductID { get; set; }
        public Nullable<int> billID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> billProductQuantity { get; set; }
        public Nullable<double> billProductPrice { get; set; }
        public Nullable<int> storeID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
